# Generated by Django 2.1.1 on 2018-10-06 02:52

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=apps.videos.models.img_dir, verbose_name='图片上传路径')),
                ('sr_video', models.FileField(upload_to=apps.videos.models.src_video_dir, verbose_name='源视频上传路径')),
            ],
            options={
                'verbose_name': '上传存储路径',
                'verbose_name_plural': '上传存储路径',
                'db_table': 'app_upload',
            },
        ),
    ]
