# Generated by Django 2.1.1 on 2018-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
