# Generated by Django 2.1.1 on 2018-10-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20181006_0711'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table='app_uploads',
        ),
    ]
